### ISSUE TITLE
DB Error When Importing Jira OpenAPI Spec

### ISSUE THREAD

**Issue by malstor** [frikky/Shuffle-apps#11]
When importing the Jira OpenAPI spec here: https://api.apis.guru/v2/specs/atlassian.com/jira/1001.0.0-SNAPSHOT/openapi.json

The following error occurred:
<img width="1869" alt="Screen Shot 2020-08-27 at 11 29 34 AM" src="https://user-images.githubusercontent.com/8838513/91462841-a4ed4280-e858-11ea-8391-e43088307a37.png">

Workaround was the minimize the app by just registering only the required components for the flow.

**Comment by frikky** [comment]
Thanks! We haven't delved into too many OpenAPI issues yet, so I'm glad you're getting to testing

**Comment by frikky** [comment]
I've fixed the issue, but found some other issues while fixing it.
The OpenAPI spec might not be very easy to use yet in Shuffle because of it's size (the dropdown will be huge). 

Here's the issue for that: https://github.com/frikky/Shuffle/issues/127

I'll push the update to Dockerhub sometime tomorrow to be useable :)

**Comment by frikky** [comment]
Updates have been pushed! How to update: https://shuffler.io/docs/configuration#updating_shuffle
